### PR TITLE
Add upstream patch to kick tray clients earlier (upstream #4159)

### PR DESCRIPTION
**Pull request by dmoerner**
There was a regression in i3 4.18.2 which causes some problems with tray icons disappearing (https://github.com/i3/i3/issues/4159). Note that this is a different problem from the existing Qubes issue with VM tray icons disappearing on i3 restart (https://github.com/QubesOS/qubes-issues/issues/2242), although it was causing further problems on Qubes (https://github.com/QubesOS/qubes-issues/issues/2242#issuecomment-707247291).

This pull request includes upstream commit https://github.com/i3/i3/commit/838b600fead202416013db5c1b57f7031f06bed6.patch, which fixes the upstream issue.

I bumped the rel number but did not update the Debian changelog because it was unclear to me what that means for a dom0 package.

### CODE REVIEW

**Comment by fepitre** [comment]
@dmoerner You need to sign your commit. Please have a look here: https://www.qubes-os.org/doc/code-signing/#using-pgp-with-git

**Comment by dmoerner** [comment]
Ugh, sorry. Somehow I introduced a typo in my gitconfig file which caused the signing to use the wrong ID. I force-pushed an amended commit, github now shows it as verified, I'm not sure if Travis will update or if there's still some issue with my key.

**Comment by marmarek** [comment]
It will update as soon as keyservers will be usable again. Just kidding, it won't happen. Can you post the pubkey somewhere (can be even here as a comment), I will add it to the local cache... (unfortunately github publish only stripped down version)

**Comment by dmoerner** [comment]
Right, here's the pubkey: https://moerner.com/moerner-publickey.txt

**Review by marmarek — APPROVED** [review]

**Pull request merged**
